config/routes.rb
Rails.application.routes.draw do
  resources :tempdbs
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/tempdb.rb
class Tempdb < ApplicationRecord
  after_save :broadcast

    def broadcast
        ActionCable.server.broadcast "tempchannel", data: temp
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/tempdbs_controller.rb
class TempdbsController < ApplicationController
  before_action :set_tempdb, only: [:show, :edit, :update, :destroy]

  # GET /tempdbs
  # GET /tempdbs.json
  def index
    @tempdbs = Tempdb.all
  end

  # GET /tempdbs/1
  # GET /tempdbs/1.json
  def show
  end

  # GET /tempdbs/new
  def new
    @tempdb = Tempdb.new
  end

  # GET /tempdbs/1/edit
  def edit
  end

  # POST /tempdbs
  # POST /tempdbs.json
  def create
    @tempdb = Tempdb.new(tempdb_params)

    respond_to do |format|
      if @tempdb.save
        format.html { redirect_to @tempdb, notice: 'Tempdb was successfully created.' }
        format.json { render :show, status: :created, location: @tempdb }
      else
        format.html { render :new }
        format.json { render json: @tempdb.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tempdbs/1
  # PATCH/PUT /tempdbs/1.json
  def update
    respond_to do |format|
      if @tempdb.update(tempdb_params)
        format.html { redirect_to @tempdb, notice: 'Tempdb was successfully updated.' }
        format.json { render :show, status: :ok, location: @tempdb }
      else
        format.html { render :edit }
        format.json { render json: @tempdb.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tempdbs/1
  # DELETE /tempdbs/1.json
  def destroy
    @tempdb.destroy
    respond_to do |format|
      format.html { redirect_to tempdbs_url, notice: 'Tempdb was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tempdb
      @tempdb = Tempdb.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def tempdb_params
      params.require(:tempdb).permit(:temp)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tempdbs_helper.rb
module TempdbsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TemperatureApp</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tempdbs/_form.html.erb
<%= form_with(model: tempdb, local: true) do |form| %>
  <% if tempdb.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(tempdb.errors.count, "error") %> prohibited this tempdb from being saved:</h2>

      <ul>
      <% tempdb.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :temp %>
    <%= form.text_field :temp, id: :tempdb_temp %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/tempdbs/edit.html.erb
<h1>Editing Tempdb</h1>

<%= render 'form', tempdb: @tempdb %>

<%= link_to 'Show', @tempdb %> |
<%= link_to 'Back', tempdbs_path %>

app/views/tempdbs/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Temperaturen</h1>

<!--<table>
  <thead>
    <tr>
      <th>Temp</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @tempdbs.each do |tempdb| %>
      <tr>
        <td><%= tempdb.temp %></td>
        <td><%= link_to 'Show', tempdb %></td>
        <td><%= link_to 'Edit', edit_tempdb_path(tempdb) %></td>
        <td><%= link_to 'Destroy', tempdb, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Tempdb', new_tempdb_path %>-->

<br>

<div>
  <canvas id="myChart" width="400" height="400"></canvas>
</div>

app/views/tempdbs/new.html.erb
<h1>New Tempdb</h1>

<%= render 'form', tempdb: @tempdb %>

<%= link_to 'Back', tempdbs_path %>

app/views/tempdbs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Temp:</strong>
  <%= @tempdb.temp %>
</p>

<%= link_to 'Edit', edit_tempdb_path(@tempdb) %> |
<%= link_to 'Back', tempdbs_path %>